language: objective-c
matrix:
  include:
    - osx_image: xcode7.1
    - osx_image: xcode7.2
    - osx_image: xcode7.3
    - osx_image: xcode8
env:
  global:
    - LC_CTYPE=en_US.UTF-8

script:
  - pod repo update
  - pod spec lint SwiftFlux.podspec
  - set -o pipefail
  - xcodebuild -project SwiftFlux.xcodeproj -scheme SwiftFlux-iOS -destination 'platform=iOS Simulator,name=iPhone 6' clean test
  - xcodebuild -project SwiftFlux.xcodeproj -scheme SwiftFlux-macOS clean test

notifications:
  email: false
